---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
    name: aapen.helse.sporbar.utbetaling
    namespace: tbd
    labels:
        team: tbd
spec:
    pool: nav-prod
    config:  # optional; all fields are optional too; defaults shown
        cleanupPolicy: delete  # delete, compact
        minimumInSyncReplicas: 1
        partitions: 3
        replication: 2  # see min/max requirements
        retentionBytes: -1  # -1 means unlimited
        retentionHours: 168  # -1 means unlimited
    acl:
        - team: tbd
          application: sporbar
          access: readwrite
        - team: flex
          application: spinnsyn-backend
          access: read
