apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sporbar
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/sporbar/default
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvsporbar
      - mountPath: /var/run/secrets/nais.io/azure
        kvPath: /azuread/data/dev/creds/sporbar
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-sporbar-v1
  - name: KAFKA_RESET_POLICY
    value: earliest
  - name: DATABASE_HOST
    value: b27dbvl016.preprod.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: sporbar
  - name: DATABASE_VAULT_MOUNT_PATH
    value: postgresql/preprod-fss/
