apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sporbar
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  vault:
    enabled: true
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-sporbar-v1
  - name: KAFKA_RESET_POLICY
    value: none
  - name: DATABASE_HOST
    value: A01DBVL014.adeo.no
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: sporbar
  - name: DATABASE_VAULT_MOUNT_PATH
    value: postgresql/prod-fss/
