name: Aiven config

on:
  push:
    branches:
    - master
    paths:
    - 'deploy/aiven-dev-utbetaling.yml'
    - 'deploy/aiven-dev-vedtak.yml'
    - 'deploy/aiven-dev-inntektsmeldingstatus.yml'
    - 'deploy/aiven-prod-utbetaling.yml'
    - 'deploy/aiven-prod-vedtak.yml'
    - 'deploy/aiven-prod-inntektsmeldingstatus.yml'
    - 'deploy/aiven-prod-sis.yml'
    - 'deploy/aiven-dev-sis.yml'

jobs:
  deployDev:
    name: apply dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/aiven-dev-utbetaling.yml,deploy/aiven-dev-vedtak.yml,deploy/aiven-dev-inntektsmeldingstatus.yml,deploy/aiven-dev-sis.yml

  deployProd:
    name: apply prod-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/aiven-prod-utbetaling.yml,deploy/aiven-prod-vedtak.yml,deploy/aiven-prod-inntektsmeldingstatus.yml,deploy/aiven-prod-sis.yml

