#name: Aiven config
#
#on:
#  push:
#    branches:
#    - master
#    paths:
#    - 'deploy/aiven-dev.yml' #TODO
#
#jobs:
#  deployDev:
#    name: apply dev-gcp
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-gcp
#          RESOURCE: deploy/aiven-dev.yml
#
#  deployProd:
#    name: apply prod-gcp
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: deploy/aiven-prod.yml
